services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - DB_SOURCE=postgres://admin:password@db:5432/xyu?sslmode=disable
      - ENV=dev

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: xyu
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  migrate:
    image: migrate/migrate
    command: sh -c "migrate -path=/migrations/ -database '$$DATABASE_URL' up"
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/xyu?sslmode=disable
    volumes:
      - ./backend/db/migrations:/migrations
    depends_on:
      - db

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
    command: [ "redis-server", "--appendonly", "yes" ]

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8081"

volumes:
  postgres_data:
  redis_data: